### ISSUE TITLE
'while' excercise wincpy check ouputs confusing tip

### ISSUE THREAD

**Issue by RishaanvB** [WincAcademy/wincpy#24]
Student had a problem:
![image](https://user-images.githubusercontent.com/69298949/149297602-1c4da486-34d0-4581-9769-5232fdf76eb0.png)

Issue is only regarding the num_joey_facts tip in the wincpy check. It's telling that it misses a argument, but it does  not need an argument. 
Might be confusing for students.

**Comment by stfwn** [comment]
1. I can see the confusion. Would it be clear enough to have `AssertionError:` in front of 'tips' so that the messages are more unified? (or alternatively: remove all mention of error types) If we add an error column the tips column would always be empty in the current implementation.
2. Makes sense, feel free to update this.
3. Great idea. I made `wincpy.checks.utils.StandardChecks.n_params` and we can add this near the top of every check. I would love to receive PRs for this from mentors if they have the time.
4. I'll leave that up to you in the material.
